import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: "KisanSetu mein aapka swagat hai",
    goodMorning: "Good Morning",
    checkStatus: "Check your procurement status and queue.",

    myProduce: "My Produce",
    addProduce: "Add your produce",
procurementTitle: "Procurement Status",
procurementSubtitle: "Check the current status of your produce.",
currentStatus: "Current Status",
qualityVerification: "Quality verification of your produce is in progress.",
procurementJourney: "Procurement Journey",
completed: "Completed",
inProgress: "In Progress",
pending: "Pending",
token: "Token",
centre: "Centre",
statusUpdateNote: "You will receive a notification when the status is updated.",
viewPayment: "View Payment Status",
goDashboard: "Go to Dashboard",
    centres: "Centres",
    findCentres: "Find nearby centres",
centreTitle: "Nearby Procurement Centres",
centreSubtitle: "Choose a suitable procurement centre for you",
queue: "Queue",
estimatedWait: "Estimated Wait",
centreLoad: "Centre Load",
low: "Low",
medium: "Medium",
high: "High",
getRecommendation: "Get AI Recommendation",
    myToken: "My Token",
    noActiveToken: "No active token",

    payment: "Payment",
    checkPayment: "Check payment",

    notifications: "Notifications",
    checkNotifications: "Check latest updates",

    // Add Produce
    addProduceTitle: "Add Your Produce",
    selectProduce: "Select Produce",
    quantity: "Quantity",
    enterQuantity: "Enter quantity",
    expectedDate: "Expected Date",
    optional: "Optional",
    findCentres: "Find Centres",
    centreTitle: "Nearby Procurement Centres",
distance: "Distance",
recommendationTitle: "AI Recommended Centre",
recommendedForYou: "Recommended for you",
distance: "Distance",
recommendationTitle: "AI Recommended Centre",
recommendedForYou: "Recommended for You",
distance: "Distance",
currentQueue: "Current Queue",
slotBookingTitle: "Book Your Slot",
selectDate: "Select Date",
availableTimeSlots: "Available Time Slots",
slotsAvailable: "slots available",
confirmSlotBooking: "Confirm Slot Booking",
selectDateAlert: "Please select a date",
selectTimeAlert: "Please select a time slot",
slotSubtitle: "Select a convenient date and time",
estimatedWait: "Estimated Wait",
centreLoad: "Centre Load",
recommendedSlot: "Recommended Slot",
recommendedDate: "Recommended Date",
chooseSlot: "Choose This Slot",
currentQueue: "Current Queue",
estimatedWait: "Estimated Wait",
slotBookingTitle: "Book Procurement Slot",
selectSlot: "Select a Slot",
available: "Available",
slots: "slots",
procurementTitle: "Procurement Tracking",
procurementSubtitle: "Track your procurement journey",
registration: "Registration",
slotBooked: "Slot Booked",
arrivedAtCentre: "Arrived at Centre",
qualityCheck: "Quality Check",
procurement: "Procurement",
payment: "Payment",
completed: "Completed",
currentStage: "Current Stage",
viewPayment: "View Payment Status",
bookingNote: "Select a convenient time slot for procurement.",
confirmBooking: "Confirm Booking",
centreLoad: "Centre Load",
recommendedSlot: "Recommended Slot",
recommendedDate: "Recommended Date",
bookSlot: "Book This Slot",
queue: "Queue",
estimatedWait: "Estimated Wait",
load: "Load",
low: "Low",
tokenTitle: "Booking Confirmed",
tokenSubtitle: "Your procurement slot has been successfully booked.",
digitalToken: "Your Digital Token",
confirmed: "Confirmed",
centre: "Centre",
date: "Date",
slot: "Slot",
liveQueueTitle: "Live Queue",
realTimeQueue: "Real-time procurement queue",
yourToken: "Your Token",
currentlyServing: "Currently Serving",
farmersAhead: "Farmers Ahead",
estimatedWait: "Estimated Wait",
queueStatus: "Queue Status",
paymentTitle: "Payment Status",
paymentSubtitle: "Track your procurement payment",
paymentDetails: "Payment Details",
produce: "Produce",
quantity: "Quantity",
rate: "Rate",
totalAmount: "Total Amount",
status: "Status",
processing: "Processing",
transactionId: "Transaction ID",
expectedPaymentDate: "Expected Payment Date",
withinWorkingDays: "Within 2 working days",
paymentNote: "Your payment is being processed. You will be notified once it is credited.",
backDashboard: "Go to Dashboard",
movingNormally: "Moving Normally",
notificationTitle: "Notifications",
notificationSubtitle: "Latest updates about your procurement",
slotBookingConfirmed: "Slot Booking Confirmed",
queueUpdated: "Queue Updated",
turnApproaching: "Turn Approaching",
qualityCheck: "Quality Check",
paymentUpdate: "Payment Update",
newNotification: "NEW",
queueProgressing: "Queue is progressing normally",
lastUpdated: "Last updated",
yourPosition: "Your position",
turnEstimate: "Your turn may take approximately",
minutes: "minutes",
turnNotification: "KisanSetu will notify you when your turn is approaching.",
refreshQueue: "Refresh Queue",
goDashboard: "Go to Dashboard",
liveQueueTitle: "Live Queue",
currentToken: "Current Token",
myToken: "My Token",
farmersAhead: "Farmers Ahead",
estimatedWait: "Estimated Wait",
queueStatus: "Queue Status",
movingNormally: "Moving Normally",
lastUpdated: "Last Updated",
justNow: "Just now",
queueProgress: "Queue Progress",
refreshQueue: "Refresh Queue",
queuePosition: "Queue Position",
farmersAhead: "Farmers Ahead",
estimatedWait: "Estimated Wait",
queueUpdateNote: "You will receive queue updates and turn approaching notifications.",
viewLiveQueue: "View Live Queue",
goDashboard: "Go to Dashboard",
paymentSubtitle: "Track your procurement payment",
paymentProcessingMessage: "Your payment is being processed.",
totalProcurementAmount: "Total Procurement Amount",
paymentDetails: "Payment Details",
rate: "Rate",
transactionId: "Transaction ID",
expectedPayment: "Expected Payment",
viewProcurementStatus: "View Procurement Status",
tokenTitle: "Booking Confirmed",
tokenSubtitle: "Your procurement slot has been successfully booked.",
digitalToken: "Your Digital Token",
confirmed: "Confirmed",
centre: "Centre",
date: "Date",
slot: "Slot",
queuePosition: "Queue Position",
farmersAhead: "Farmers Ahead",
estimatedWait: "Estimated Wait",
queueUpdateNote: "You will receive queue updates and turn approaching notifications.",
viewLiveQueue: "View Live Queue",
goDashboard: "Go to Dashboard",
medium: "Medium",
high: "High",
loading: "Loading...",
somethingWrong: "Something went wrong",
tryAgain: "Try Again",
noData: "No data available",
noSlots: "No slots available",
selectAnotherDate: "Try another date",
notificationTitle: "Notifications",
notificationSubtitle: "Latest updates about your procurement",
slotBookingConfirmed: "Slot Booking Confirmed",
queueUpdated: "Queue Updated",
turnApproaching: "Turn Approaching",
qualityCheck: "Quality Check",
paymentUpdate: "Payment Update",
newNotification: "NEW",
viewRecommendation: "View Recommendation",

    language: "हिंदी",
  },

  hi: {
    welcome: "किसानसेतु में आपका स्वागत है",
    goodMorning: "सुप्रभात",
    notificationTitle: "सूचनाएं",
notificationSubtitle: "आपकी खरीद से जुड़े नवीनतम अपडेट",
slotBookingConfirmed: "स्लॉट बुकिंग की पुष्टि",
queueUpdated: "कतार अपडेट",
turnApproaching: "आपकी बारी आने वाली है",
qualityCheck: "गुणवत्ता जांच",
paymentUpdate: "भुगतान अपडेट",
newNotification: "नया",
    checkStatus: "अपनी खरीद स्थिति और कतार देखें।",
centreTitle: "नजदीकी खरीद केंद्र",
distance: "दूरी",
queue: "कतार",
slotBookingTitle: "खरीद स्लॉट बुक करें",
selectSlot: "स्लॉट चुनें",
available: "उपलब्ध",
slots: "स्लॉट",
tokenTitle: "बुकिंग की पुष्टि हो गई",
tokenSubtitle: "आपका खरीद स्लॉट सफलतापूर्वक बुक हो गया है।",
digitalToken: "आपका डिजिटल टोकन",
confirmed: "पुष्टि हो गई",
centre: "केंद्र",
date: "तारीख",
slot: "स्लॉट",
loading: "लोड हो रहा है...",
somethingWrong: "कुछ गलत हो गया",
tryAgain: "पुनः प्रयास करें",
noData: "कोई डेटा उपलब्ध नहीं है",
noSlots: "कोई स्लॉट उपलब्ध नहीं है",
selectAnotherDate: "दूसरी तारीख चुनें",
queuePosition: "कतार स्थिति",
liveQueueTitle: "लाइव कतार",
currentToken: "वर्तमान टोकन",
myToken: "मेरा टोकन",
farmersAhead: "आगे किसान",
estimatedWait: "अनुमानित प्रतीक्षा",
queueStatus: "कतार स्थिति",
movingNormally: "सामान्य रूप से चल रही है",
lastUpdated: "अंतिम अपडेट",
justNow: "अभी",
procurementTitle: "खरीद की स्थिति",
procurementSubtitle: "अपनी उपज की वर्तमान स्थिति देखें।",
currentStatus: "वर्तमान स्थिति",
qualityVerification: "आपकी उपज की गुणवत्ता जांच चल रही है।",
procurementJourney: "खरीद प्रक्रिया",
completed: "पूरा हुआ",
inProgress: "प्रगति में",
pending: "लंबित",
token: "टोकन",
centre: "केंद्र",
notificationTitle: "सूचनाएं",
notificationSubtitle: "आपकी खरीद से जुड़े नवीनतम अपडेट",
slotBookingConfirmed: "स्लॉट बुकिंग की पुष्टि",
queueUpdated: "कतार अपडेट",
turnApproaching: "आपकी बारी आने वाली है",
qualityCheck: "गुणवत्ता जांच",
paymentUpdate: "भुगतान अपडेट",
newNotification: "नया",
paymentTitle: "भुगतान की स्थिति",
paymentSubtitle: "अपनी खरीद के भुगतान को ट्रैक करें",
paymentDetails: "भुगतान विवरण",
produce: "उपज",
quantity: "मात्रा",
rate: "दर",
totalAmount: "कुल राशि",
status: "स्थिति",
processing: "प्रक्रिया में",
transactionId: "लेनदेन आईडी",
expectedPaymentDate: "अपेक्षित भुगतान तारीख",
withinWorkingDays: "2 कार्य दिवसों के भीतर",
paymentNote: "आपका भुगतान प्रक्रिया में है। राशि जमा होने पर आपको सूचना दी जाएगी।",
backDashboard: "डैशबोर्ड पर जाएं",
statusUpdateNote: "स्थिति अपडेट होते ही आपको सूचना मिलेगी।",
viewPayment: "भुगतान की स्थिति देखें",
goDashboard: "डैशबोर्ड पर जाएं",
queueProgress: "कतार प्रगति",
refreshQueue: "कतार अपडेट करें",
farmersAhead: "आगे किसान",
estimatedWait: "अनुमानित प्रतीक्षा",
queueUpdateNote: "आपको कतार अपडेट और आपकी बारी आने की सूचनाएं मिलती रहेंगी।",
viewLiveQueue: "लाइव कतार देखें",
goDashboard: "डैशबोर्ड पर जाएं",
tokenTitle: "बुकिंग की पुष्टि हो गई",
tokenSubtitle: "आपका खरीद स्लॉट सफलतापूर्वक बुक हो गया है।",
digitalToken: "आपका डिजिटल टोकन",
confirmed: "पुष्टि हो गई",
centre: "केंद्र",
date: "तारीख",
slot: "स्लॉट",
liveQueueTitle: "लाइव कतार",
realTimeQueue: "रियल-टाइम खरीद कतार",
yourToken: "आपका टोकन",
currentlyServing: "वर्तमान में सेवा",
farmersAhead: "आगे किसान",
estimatedWait: "अनुमानित प्रतीक्षा",
queueStatus: "कतार स्थिति",
procurementTitle: "खरीद की स्थिति",
procurementSubtitle: "अपनी खरीद प्रक्रिया को ट्रैक करें",
registration: "पंजीकरण",
slotBooked: "स्लॉट बुक",
arrivedAtCentre: "केंद्र पर पहुंचे",
qualityCheck: "गुणवत्ता जांच",
procurement: "खरीद",
payment: "भुगतान",
completed: "पूरा हुआ",
currentStage: "वर्तमान चरण",
viewPayment: "भुगतान की स्थिति देखें",
movingNormally: "सामान्य रूप से चल रही है",
queueProgressing: "कतार सामान्य रूप से आगे बढ़ रही है",
lastUpdated: "अंतिम अपडेट",
yourPosition: "आपकी स्थिति",
turnEstimate: "आपकी बारी आने में लगभग",
minutes: "मिनट",
turnNotification: "आपकी बारी पास आने पर किसानसेतु आपको सूचित करेगा।",
refreshQueue: "कतार अपडेट करें",
goDashboard: "डैशबोर्ड पर जाएं",liveQueueTitle: "लाइव कतार",
realTimeQueue: "रियल-टाइम खरीद कतार",
yourToken: "आपका टोकन",
currentlyServing: "वर्तमान में सेवा",
farmersAhead: "आगे किसान",
estimatedWait: "अनुमानित प्रतीक्षा",
queueStatus: "कतार स्थिति",
movingNormally: "सामान्य रूप से चल रही है",
queueProgressing: "कतार सामान्य रूप से आगे बढ़ रही है",
lastUpdated: "अंतिम अपडेट",
yourPosition: "आपकी स्थिति",
turnEstimate: "आपकी बारी आने में लगभग",
minutes: "मिनट",
turnNotification: "आपकी बारी पास आने पर किसानसेतु आपको सूचित करेगा।",
refreshQueue: "कतार अपडेट करें",
goDashboard: "डैशबोर्ड पर जाएं",
queuePosition: "कतार स्थिति",
farmersAhead: "आगे किसान",
estimatedWait: "अनुमानित प्रतीक्षा",
queueUpdateNote: "आपको कतार अपडेट और आपकी बारी आने की सूचनाएं मिलती रहेंगी।",
viewLiveQueue: "लाइव कतार देखें",
goDashboard: "डैशबोर्ड पर जाएं",
bookingNote: "खरीद के लिए सुविधाजनक समय स्लॉट चुनें।",
confirmBooking: "बुकिंग की पुष्टि करें",
estimatedWait: "अनुमानित प्रतीक्षा",
load: "लोड",
low: "कम",
medium: "मध्यम",
high: "अधिक",
recommendationTitle: "AI द्वारा अनुशंसित केंद्र",
recommendedForYou: "आपके लिए अनुशंसित",
distance: "दूरी",
currentQueue: "वर्तमान कतार",
estimatedWait: "अनुमानित प्रतीक्षा",
centreLoad: "केंद्र लोड",
recommendedSlot: "अनुशंसित स्लॉट",
recommendedDate: "अनुशंसित तारीख",
bookSlot: "यह स्लॉट बुक करें",
viewRecommendation: "सिफारिश देखें",
    myProduce: "मेरी उपज",
    recommendationTitle: "AI द्वारा अनुशंसित केंद्र",
recommendedForYou: "आपके लिए अनुशंसित",
distance: "दूरी",
slotBookingTitle: "अपना स्लॉट बुक करें",
selectDate: "तारीख चुनें",
availableTimeSlots: "उपलब्ध समय स्लॉट",
slotsAvailable: "स्लॉट उपलब्ध",
confirmSlotBooking: "स्लॉट बुकिंग की पुष्टि करें",
selectDateAlert: "कृपया तारीख चुनें",
selectTimeAlert: "कृपया समय स्लॉट चुनें",
slotSubtitle: "अपनी सुविधाजनक तारीख और समय चुनें",
currentQueue: "वर्तमान कतार",
estimatedWait: "अनुमानित प्रतीक्षा",
centreLoad: "केंद्र लोड",
recommendedSlot: "अनुशंसित स्लॉट",
recommendedDate: "अनुशंसित तारीख",
chooseSlot: "यह स्लॉट चुनें",
    addProduce: "अपनी उपज जोड़ें",
centreTitle: "नजदीकी खरीद केंद्र",
centreSubtitle: "अपने लिए उपयुक्त खरीद केंद्र चुनें",
queue: "कतार",
estimatedWait: "अनुमानित प्रतीक्षा",
centreLoad: "केंद्र लोड",
low: "कम",
medium: "मध्यम",
high: "अधिक",
getRecommendation: "AI सिफारिश प्राप्त करें",
    centres: "केंद्र",
    findCentres: "नजदीकी केंद्र खोजें",

    myToken: "मेरा टोकन",
    noActiveToken: "कोई सक्रिय टोकन नहीं है",

    payment: "भुगतान",
    checkPayment: "भुगतान की स्थिति देखें",

    notifications: "सूचनाएं",
    checkNotifications: "नवीनतम अपडेट देखें",

    // Add Produce
    addProduceTitle: "अपनी उपज जोड़ें",
    selectProduce: "उपज चुनें",
    quantity: "मात्रा",
    enterQuantity: "मात्रा दर्ज करें",
    expectedDate: "अपेक्षित तारीख",
    optional: "वैकल्पिक",
    findCentres: "केंद्र खोजें",

    language: "English",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem("language") || "en"
  );

  const toggleLanguage = () => {
    const newLanguage = language === "en" ? "hi" : "en";

    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        toggleLanguage,
        t: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}